"""Elydora Python SDK — tamper-evident audit trail for AI agents."""

from .client import ElydoraClient
from .async_client import AsyncElydoraClient
from .errors import ElydoraError
from .crypto import (
    compute_chain_hash,
    compute_payload_hash,
    jcs_canonicalize,
    sha256_base64url,
    sign_ed25519,
    sign_eor,
    get_public_key_base64url,
)
from .utils import base64url_encode, base64url_decode, generate_nonce, generate_uuidv7
from .types import (
    EOR,
    EAR,
    Agent,
    AgentKey,
    AgentAssignment,
    AdminEvent,
    EpochAnchor,
    MemberEntry,
    Operation,
    Receipt,
    Epoch,
    Export,
    Organization,
    User,
    WebhookEntry,
    AdminAction,
    AgentStatus,
    ExportStatus,
    IntegrationType,
    KeyStatus,
    RbacRole,
    RegisterAgentRequest,
    RegisterAgentResponse,
    UpdateAgentRequest,
    UpdateAgentResponse,
    GetAgentResponse,
    ListAgentsResponse,
    DeleteAgentResponse,
    FreezeAgentResponse,
    UnfreezeAgentResponse,
    SubmitOperationResponse,
    GetOperationResponse,
    VerifyOperationResponse,
    AuditQueryResponse,
    GetEpochResponse,
    ListEpochsResponse,
    CreateExportResponse,
    GetExportResponse,
    ListExportsResponse,
    ListWebhooksResponse,
    RegisterWebhookResponse,
    ListMembersResponse,
    ListAdminEventsResponse,
    JWKSResponse,
    AuthRegisterResponse,
    AuthLoginResponse,
    GetMeResponse,
    IssueApiTokenResponse,
    RotateApiTokenResponse,
    IssueTokenResponse,
    RotateTokenResponse,
    HealthResponse,
    DeepHealthResponse,
)

__version__ = "1.2.0"

__all__ = [
    "ElydoraClient",
    "AsyncElydoraClient",
    "ElydoraError",
    "compute_chain_hash",
    "compute_payload_hash",
    "jcs_canonicalize",
    "sha256_base64url",
    "sign_ed25519",
    "sign_eor",
    "get_public_key_base64url",
    "base64url_encode",
    "base64url_decode",
    "generate_nonce",
    "generate_uuidv7",
    # Literal type aliases
    "AdminAction",
    "AgentStatus",
    "ExportStatus",
    "IntegrationType",
    "KeyStatus",
    "RbacRole",
    # Entity types
    "EOR",
    "EAR",
    "Agent",
    "AgentAssignment",
    "AgentKey",
    "AdminEvent",
    "EpochAnchor",
    "MemberEntry",
    "Operation",
    "Receipt",
    "Epoch",
    "Export",
    "Organization",
    "User",
    "WebhookEntry",
    # Request types
    "RegisterAgentRequest",
    "UpdateAgentRequest",
    # Response types
    "RegisterAgentResponse",
    "UpdateAgentResponse",
    "GetAgentResponse",
    "ListAgentsResponse",
    "DeleteAgentResponse",
    "FreezeAgentResponse",
    "UnfreezeAgentResponse",
    "SubmitOperationResponse",
    "GetOperationResponse",
    "VerifyOperationResponse",
    "AuditQueryResponse",
    "GetEpochResponse",
    "ListEpochsResponse",
    "CreateExportResponse",
    "GetExportResponse",
    "ListExportsResponse",
    "ListWebhooksResponse",
    "RegisterWebhookResponse",
    "ListMembersResponse",
    "ListAdminEventsResponse",
    "JWKSResponse",
    "AuthRegisterResponse",
    "AuthLoginResponse",
    "GetMeResponse",
    "IssueApiTokenResponse",
    "RotateApiTokenResponse",
    "IssueTokenResponse",
    "RotateTokenResponse",
    "HealthResponse",
    "DeepHealthResponse",
]
